base_url = "https://lemonsh.moe"
compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"
feed_limit = 20
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
external_links_target_blank = true
external_links_no_referrer = true

[extra]
comments = true
nav = [
    { path = "/", label = "home" },
    { path = "/blog/", label = "blog" },
]
