base_url = "https://lemonsh.moe"
compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]
feed_limit = 20
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "highlight.css" },
]
external_links_target_blank = true
external_links_no_referrer = true

[extra]
comments = true
nav = [
    { path = "/", label = "home" },
    { path = "/projects/", label = "projects" },
    { path = "/blog/", label = "blog" },
]
