base_url = "https://lemonsh.moe"
compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = true
highlight_theme = "1337"
external_links_target_blank = true
external_links_no_referrer = true

[extra]
nav = [
    { path = "/", label = "home" },
    { path = "/blog/", label = "blog" },
]
